<?php
namespace App\Http\Controllers\Auth;

use XiaohuiLam\Laravel\WechatAppLogin\Facade;
use XiaohuiLam\Laravel\WechatAppLogin\Http\Controllers\Auth\WechatLoginController as BaseWechatLoginController;
use Illuminate\Support\Str;

class WechatLoginController extends BaseWechatLoginController
{

    public function login()
    {
        /**
         * @var \EasyWeChat\MiniProgram\Application $wechat
         */
        $response = Facade::login('011vmd0w3eka903KKK2w3Brdeu4vmd0F');
        $openid = data_get($response, 'openid');
        if (!$openid) {
            return response()->error(403, 'bad code');
        }
//        return parent::login(); // TODO: Change the autogenerated stub
    }

    /**
     * 注册用户时的attribtues
     *
     * @param array $credential
     * @return array
     */
    protected function userAttributes($credential)
    {
        $attributes = $credential;

//        $name = Str::random(8);
//        $attributes['name'] = $name;
//        $attributes['email'] = $name . '@wechat.com';

        \Log::info($attributes);
        return $attributes;
    }
}
