<?php

namespace App\Admin\Grid\Tools;

use App\Admin\Forms\Salestarget;
use Dcat\Admin\Grid\Tools\AbstractTool;
use Dcat\Admin\Widgets\Modal;

class NccSaleTool extends AbstractTool
{

    public function render()
    {
//        return parent::render(); // TODO: Change the autogenerated stub
        return Modal::make()
            ->lg()
            ->title('导入Ncc数据 - 不要改变Ncc导出数据格式')
            ->body(Salestarget::make())
            ->button('<button class="btn btn-primary grid-refresh btn-mini"><i class="feather icon-file-plus"></i><span class="d-none d-sm-inline">&nbsp; 导入Ncc数据</span></button>');
    }

//    public function handle(Request $request)
//    {
//        // 你的代码逻辑
////        $a = VlwApiServer::GetRobotList();
////        Server::updateBot($a);
//        dd($request->all());
//        return $this->response()->success('发送成功')->refresh();
//    }
}
