<?php

namespace App\Admin\Grid\Tools;

use App\Admin\Forms\Salestarget;
use App\Servers\Server;
use App\Wechats\VlwApiServer;
use Dcat\Admin\Grid\Tools\AbstractTool;
use Dcat\Admin\Widgets\Modal;
use Illuminate\Http\Request;

class SalestargetTool extends AbstractTool
{

    public function render()
    {
//        return parent::render(); // TODO: Change the autogenerated stub
        return Modal::make()
            ->lg()
            ->title('导入门店任务，门店编号，任务，时间时间，结束时间，状态1')
            ->body(Salestarget::make())
            ->button('<button class="btn btn-primary grid-refresh btn-mini"><i class="feather icon-file-plus"></i><span class="d-none d-sm-inline">&nbsp; 导入门店任务</span></button>');
    }

//    public function handle(Request $request)
//    {
//        // 你的代码逻辑
////        $a = VlwApiServer::GetRobotList();
////        Server::updateBot($a);
//        dd($request->all());
//        return $this->response()->success('发送成功')->refresh();
//    }
}
